name: End-to-end tests
on: push
  
jobs:
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - name: Rodando testes
        run: npm run test -- --spec cypress/e2e/barriga/** --browser chrome
        
