name: End-to-end tests
on: 
  schedule:
    - cron:  '35 12 * * *'
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          name: Chrome
          on: commit
