name: End-to-end tests
on: push
  
jobs:
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/barriga/backend.cy.js
          browser: chrome
